name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 15.206.94.233
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/cloud-ecommerce-app
            git pull origin main
            sudo fuser -k 5000/tcp || true
            nohup python3 run.py > app.log 2>&1 &
            echo "Deployed!"
            